const days = [['DAY 01','2.11 THU','RUSUTSU','ルスツで滑走'],['DAY 02','2.12 FRI','NISEKO','ニセコで滑走'],['DAY 03','2.13 SAT','RUSUTSU','もう一度、ルスツへ'],['DAY 04','2.14 SUN','SAPPORO','札幌を観光']];
const members = ['たくと','いさむ','あさ','たみだ'];
export default function Home() { return <main>
  <section className="hero" id="top"><nav className="shell nav"><a className="brand" href="#top">SNOW <i>TRIP</i></a><div><a href="#schedule">SCHEDULE</a><a href="#stay">STAY</a><a href="#crew">CREW</a></div></nav><div className="shell copy"><p>2027.02.11 — 02.14 / HOKKAIDO</p><h1>雪山へ、<br/><em>4 DAYS.</em></h1><strong>RUSUTSU · NISEKO · SAPPORO<br/>4人でつくる、冬のしおり。</strong><a className="button" href="#schedule">旅の予定を見る ↓</a></div><div className="mountains"><b/><b/><b/></div></section>
  <section className="intro shell"><p>THE PLAN</p><div><h2>滑って、温まって、<br/>最後は札幌を歩く。</h2><span>ルスツとニセコで3日間のスキー・スノーボード。ホテル甘露の森を拠点に、最終日は札幌へ。</span></div><aside><b>02.11</b><small>THU</small><i>→</i><b>02.14</b><small>SUN</small></aside></section>
  <section className="schedule" id="schedule"><div className="shell"><p>DAY BY DAY</p><h2>予定は、<em>雪</em>とともに。</h2></div><div className="shell cards">{days.map(([day,date,place,title],i)=><article className={`card c${i}`} key={day}><header><span>{day}</span><span>{date}</span></header><p>{place}</p><h3>{title}</h3></article>)}</div></section>
  <section className="stay shell" id="stay"><div><p>BASE CAMP</p><h2>泊まる場所も、<br/>旅の楽しみ。</h2></div><div className="lodging"><article><p>02.11 — 02.13 / 2 NIGHTS</p><h3>ホテル甘露の森</h3><span>ニセコ昆布温泉</span></article><article><p>02.13 — 02.14 / 1 NIGHT</p><h3>アパホテル＆リゾート〈札幌〉</h3><span>札幌の夜を楽しむ</span></article></div></section>
  <section className="rental" id="rental"><div className="shell rental-wrap"><div><p>RENTAL CAR</p><h2>雪道をつなぐ、<br/><em>4日間の相棒。</em></h2><span>新千歳空港からルスツ、ニセコ、札幌へ。4人の旅をレンタカーでつなぐ。</span></div><div className="rent-card"><div className="rent-route"><strong>NEW CHITOSE AIRPORT</strong><i>→</i><strong>HOKKAIDO ROAD TRIP</strong></div><dl><div><dt>受取</dt><dd>2.11 THU 10:00</dd></div><div><dt>返却</dt><dd>2.14 SUN 17:00</dd></div><div><dt>営業所</dt><dd>新千歳空港店</dd></div><div><dt>営業時間・送迎</dt><dd>08:00 — 22:00</dd></div></dl><div className="price"><span>4名 / 3泊4日</span><strong>¥42,500</strong><small>税込・安心パック込み</small></div><ul><li>基本料金 ¥38,500（免責補償・消費税込み）</li><li>安心パック（ミニバン・ワゴン）¥4,000</li><li>予約時支払いなし・受取時に店舗精算</li><li>前日までにSMS等で送迎案内予定</li></ul></div></div></section>
  <section className="crew" id="crew"><div className="shell"><div><p>THE CREW</p><h2>4人で、<br/><em>いい冬にする。</em></h2></div><aside>{members.map((m,i)=><span key={m}>0{i+1} <b>{m}</b></span>)}</aside></div></section>
  <footer className="shell"><span>2027 HOKKAIDO SNOW TRIP</span><a href="#top">BACK TO TOP ↑</a></footer>
</main>; }
